services:
  backend:
#    image: 192.168.56.103:8082/absence-backend:latest
    build:
      context: ./Back_end
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/absence.crt:/etc/ssl/certs/absence.crt
      - ./certs/absence.key:/etc/ssl/private/absence.key
      - ./modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf
      - ./modsecurity/crs-setup.conf:/etc/modsecurity/crs-setup.conf
      - ./modsecurity/rules:/etc/modsecurity/rules
      - ./modsecurity/logs:/var/log/modsecurity
    depends_on:
      - backend
    networks:
      - net

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
  #   frontend:
  #     build:
  #       context: ./Front_end
  #       dockerfile: Dockerfile
  #     networks:
  #       - net
  #     depends_on:
  #       - backend
networks:
  net:

volumes:
  pgdata:
